---
- hosts: bastion
  tasks:
    - name: Get all hosts
      ansible.builtin.shell: "cat /root/redhat-lab/myhosts"
      register: hosts

    - name: Create DNS record
      vars:
        ansible_connection: winrm
        ansible_user: administrator 
        ansible_password: redhat@123
        ansible_port: 5985
        ansible_winrm_transport: ntlm
      delegate_to: ad01
      community.windows.win_dns_record:
        name: "{{ item | split(' ') | last }}"
        type: "A"
        value: "{{ item | split(' ') | first }}"
        zone: "jferre.local"
      loop: "{{ hosts.stdout_lines }}"
