# https://docs.ansible.com/ansible/latest/collections/ansible/windows/win_user_module.html
---
- name: Playbook de teste para o pessoal
  gather_facts: false
  hosts: all
  vars:
    #ansible_connection: winrm
    #ansible_user: administrator 
    #ansible_password: redhat@123
    #ansible_port: 5985
    #ansible_winrm_transport: ntlm
    usuario_espelho: Joao Ferreira
  tasks:
    - name: Consulta usuario espelho no AD
      microsoft.ad.object_info:
        ldap_filter: (&(Name={{ usuario_espelho }}))
        properties:
          - DistinguishedName
          - MemberOf
          #- Title
          - Department
          - Description
        search_base: DC=jferre,DC=local
      register: baseuser_info

    - name: Obter OU e grupos do usuário
      set_fact:
        ou_info: "{{ ((baseuser_info.objects | map(attribute='DistinguishedName'))[0] | split(','))[1:] | join(',') }}"
        groups_info: "{{ baseuser_info.objects | map(attribute='MemberOf') }}"
        #title_info: "{{ (baseuser_info.objects | map(attribute='Title'))[0] }}"
        department_info: "{{ (baseuser_info.objects | map(attribute='Department'))[0] }}"
        description_info: "{{ (baseuser_info.objects | map(attribute='Description'))[0] }}"

    - debug:
        msg: "{{ item }}"
      with_items:
        - "{{ ou_info }}"
        - "{{ groups_info }}"
        #- "{{ title_info }}"
        - "{{ department_info }}"
        - "{{ description_info }}"

    - name: Cria um novo usuário no AD com base no usuário espelho
      microsoft.ad.user:
        identity: "{{ NewUser }}"
        #firstname: "{{ firstname }}"
        #lastname: "{{ lastname }}"
        #email: "{{ email }}"
        #display_name: "{{ firstname }} {{ lastname }}"
        state: present
        password: redhat@123
        #state: present
        path: "{{ ou_info }}"
        groups:
          set: "{{ groups_info }}"
        attributes:
          set:
            #extensionAttribute1: office365
            #extensionAttribute10: "JOAO"
            #extensionAttribute11: "FERREIRA"
            #extensionAttribute12: "joao.ferreira@jferre.local"
            #accountExpires: validar formato de data
            Description: "{{ description_info }} - Chamado {{ case_number }}"
            Department: "{{ department_info }}"
            #Title: "{{ title_info | default(omit) }}" 
            #userPrincipalName: "{{ email }}"

    #- ansible.builtin.shell: 'date -d "{{ date_expire }} +2 days" +%Y-%m-%d'
    #  register: new_date

    - name: Increase 2 days in date
      ansible.windows.win_shell: '$data=Get-Date "{{ date_expire_account }}"; ($data).AddDays(2).ToString("yyyy-MM-dd")'
      register: new_date

    - name: Get new date
      set_fact:
        date_expire: "{{ new_date.stdout_lines[0] }}"

    - name: Define data de expiração para o novo usuário no AD
      ansible.windows.win_user:
        name: "{{ NewUser }}" 
        state: present
        #account_expires: '{{ "%Y-%m-%dT%H:%M:%S%z" | ansible.builtin.strftime(now().timestamp() + (60 * 60 * 24 * 60)) }}'
        account_expires: "{{ date_expire | ansible.builtin.strftime | default('never') }}"
        password_expired: true
