# https://docs.ansible.com/ansible/latest/collections/ansible/windows/win_user_module.html
---
- name: Playbook de teste para o pessoal
  gather_facts: false
  hosts: all
  vars:
    #ansible_connection: winrm
    #ansible_user: administrator 
    #ansible_password: redhat@123
    #ansible_port: 5985
    #ansible_winrm_transport: ntlm
    usuario_espelho: Joao Ferreira
  tasks:
    - name: Consulta usuario espelho no AD
      microsoft.ad.object_info:
        ldap_filter: (&(Name={{ usuario_espelho }}))
        properties:
          - DistinguishedName
          - MemberOf
          - Title
          - Department
          - Description
        search_base: DC=jferre,DC=local
      register: baseuser_info

    - debug:
        var: baseuser_info

    - name: Obter OU e grupos do usuário
      set_fact:
        ou_info: "{{ ((baseuser_info.objects | map(attribute='DistinguishedName'))[0] | split(','))[1:] | join(',') }}"
        groups_info: "{{ baseuser_info.objects | map(attribute='MemberOf') }}"
        title_info: "{{ baseuser_info.objects | map(attribute='Title') }}"
        department_info: "{{ baseuser_info.objects | map(attribute='Department') }}"
        description_info: "{{ baseuser_info.objects | map(attribute='Description') }}"

    - debug:
        msg: "{{ item }}"
      with_items:
        - "{{ ou_info }}"
        - "{{ groups_info }}"
        - "{{ title_info }}"
        - "{{ department_info }}"
        - "{{ description_info }}"

    - name: Cria um novo usuário no AD com base no usuário espelho
      microsoft.ad.user:
        identity: "{{ NewUser }}"
        firstname: "{{ firstname }}"
        lastname: "{{ lastname }}"
        email: "{{ email }}"
        display_name: "{{ firstname }} {{ lastname }}"
        password: redhat@123
        state: present
        path: "{{ ou_info }}"
        groups:
          set: "{{ groups_info }}"
        attributes:
          set:
            #extensionAttribute1: office365
            #extensionAttribute10: "JOAO"
            #extensionAttribute11: "FERREIRA"
            #extensionAttribute12: "joao.ferreira@jferre.local"
            #accountExpires: validar formato de data
            #manager: gerente quando for empregado
            Description: "{{ description_info }}"
            Department: "{{ department_info }}"
            title: "{{ title_info }}" 
            userPrincipalName: "{{ email }}"

    - name: Define data de expiração para o novo usuário no AD
      ansible.windows.win_user:
        name: "{{ NewUser }}" 
        state: present
        account_expires: '{{ "%Y-%m-%dT%H:%M:%S%z" | ansible.builtin.strftime(now().timestamp() + (60 * 60 * 24 * 60)) }}'
