---
- name: Playbook de teste para o pessoal
  gather_facts: false
  hosts: all 
  vars:
    ansible_connection: winrm
    ansible_user: administrator 
    ansible_password: redhat@123
    ansible_port: 5985
    ansible_winrm_transport: ntlm
    date_expire: "2025-11-30 00:00:00"
  tasks:
    - ansible.windows.win_shell: '$data=Get-Date "{{ date_expire }}"; ($data).AddDays(2).ToString("yyyy-MM-dd")'
      register: new_date
        
    - debug:
        var: new_date.stdout_lines[0]
